cleanup junk properly

diff --git a/src/seth/libexec/seth/seth-debug b/src/seth/libexec/seth/seth-debug
--- a/src/seth/libexec/seth/seth-debug
+++ b/src/seth/libexec/seth/seth-debug
@@ -24,12 +24,20 @@ targetTx=$(seth tx "$1")
 
 opts=()
 
+tidy() {
+    [[ "$SRCDIR" ]] && rm -rf "$SRCDIR"
+    rm -rf "$state"
+}
+
+trap tidy SIGINT SIGTERM
+
+
 if [[ -z "$SETH_NOSRC" ]]; then
   echo "fetching contract source from etherscan..."
-  COMBINEDJSON=$(TMPDIR=. mktemp)
-  if seth bundle-source "$(echo "$targetTx" | seth --field to)" > "$COMBINEDJSON"
+  SRCDIR=$(TMPDIR=. mktemp -d seth.debug.XXXX)
+  if seth bundle-source "$(echo "$targetTx" | seth --field to)" --dir "$SRCDIR" > "$SRCDIR"/combined.json
   then
-      opts+=(--source "$COMBINEDJSON")
+      opts+=(--source "$SRCDIR"/combined.json)
   else
       echo "no source available"
   fi
@@ -46,12 +54,13 @@ for i in "${txs[@]}"; do
    hash=$(echo "$tx" | seth --field hash)
 
    if [[ "$1" = "$hash" ]]; then
-     seth run-tx "$tx" --state "$state" --debug "${opts[@]}"  
+     seth run-tx "$tx" --state "$state" --debug "${opts[@]}"
+     tidy
      break
    else
      echo -en "\rtransaction ($j/$index)"
      # exit code 2 means REVERT or otherwise acceptable failure
-     seth run-tx "$tx" --state "$state" > /dev/null || [[ $? == 2 ]] || seth --fail "hevm error while executing tx: $hash"
+     seth run-tx "$tx" --state "$state" > /dev/null || [[ $? == 2 ]] || (tidy; seth --fail "hevm error while executing tx: $hash")
      j=$((j + 1))
    fi
 done
